name: lets_meet
description: CECS 491 Senior Project

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  line_awesome_flutter: ^2.0.0
  firebase_core: ^2.3.0
  cloud_firestore: ^4.1.0
  firebase_auth: ^4.1.4
  geolocator: ^9.0.2
  weather:
  http: ^0.13.3
  flutter_spinkit: ^5.0.0
  table_calendar: ^3.0.7
  intl: ^0.17.0
  google_maps_webservice: ^0.0.20-nullsafety.2
  flutter_local_notifications: ^13.0.0
  easy_search_bar: ^2.4.2
  flutter_native_timezone: ^2.0.0
  location: ^4.2.0

  search_map_location: ^0.0.6
  geocoding: ^2.0.5
  firebase_dynamic_links: ^5.0.15
  google_nav_bar: ^5.0.6
  rxdart: ^0.27.7
  google_fonts: ^4.0.4
  flutter_launcher_icons: ^0.11.0
  flutter_datetime_picker: ^1.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.11.0

  flutter_lints: ^2.0.0

flutter_icons:
  android: "launcher_icon"
  image_path: "lib/Images/LetsPlan-border.png"

flutter:

  uses-material-design: true

  assets:
    - lib/Images/LetsPlan.png
    - lib/Images/LetsPlan-border.png